name: The Tavern CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: the_tavern_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: "21.2.5"
          elixir-version: "1.8.1"
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install elixir dependencies
        run: mix deps.get
      - name: Set up database
        run: mix do ecto.create, ecto.migrate
      - name: Unit tests
        run: mix test
  e2e-tests:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: the_tavern_ci
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MIX_ENV: prod
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Swap out prod config with ci config
        run: cp config/ci.exs config/prod.exs
      - name: Set up Elixir
        uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: "21.2.5"
          elixir-version: "1.8.1"
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.2
      - name: Restore node assets dependency cache
        uses: actions/cache@v2
        with:
          path: "**/assets/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Restore elixir dependency cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install elixir dependencies
        run: mix deps.get
      - name: Build
        run: |
          mix compile
          mix do ecto.create, ecto.migrate
          (cd apps/the_tavern_web && npm ci --prefix assets)
          (cd apps/the_tavern_web && npm run deploy --prefix assets)
      - name: Restore node e2e dependency cache
        uses: actions/cache@v2
        with:
          path: e2e
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Start server in the background
        run: mix phx.server &
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: e2e
      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots
      - name: Upload cypress videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: e2e/cypress/videos
